## Hardcode the resource names to something human friendly
nameOverride: monitoring

## Watch these resources for new DNS records
sources:
  - service
  - ingress

## use google as the dns provider
provider: google

# Specify the Google project (required when provider=google)
# You'll need to create this secret containing your credentials.json
google:
  project: "msteps-website-1550665534040"
  serviceAccountSecret: "msteps-gke-external-dns-service-account-credentials"

## List of domains that can be managed. Should be managed by Google Cloud DNS
domainFilters: ["google.gradeous.io"]

# These help tell which records are owned by external-dns.
registry: "txt"
txtOwnerId: "k8s"

## Limit external-dns resources
resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m

## ensure RBAC is enabled
rbac:
  create: true
  apiVersion: v1
